### ISSUE TITLE
Keep getting errors on trying to enable!

### ISSUE THREAD

**Issue by Sylian1337** [BlenderBoi/Bonera#2]
Hello!

First off this looks like an amazing addon and think it could really help me out!

My problem is that the addon installs correctly but when I try to enable it throws errors sadly :( 

![Capture](https://user-images.githubusercontent.com/14792697/212469186-cbeb1638-4abd-4147-a76c-9cd28f65d412.PNG)

I would be really happy if you could take a look at it and tell me if I am doing something wrong or there are something else happening,

**Comment by BlenderBoi** [comment]
Try Download it Again, I made a Mistake, It Should Work Now
(Remove the Old One Before Installing the Fixed One)

Let me know if it works now

**Comment by Sylian1337** [comment]
> Try Download it Again, I made a Mistake, It Should Work Now (Remove the Old One Before Installing the Fixed One)
> 
> Let me know if it works now

Hey!

Thank you so much! It works now :D
