### ISSUE TITLE
Not working for Lattices

### ISSUE THREAD

**Issue by lucianomunoz** [BlenderBoi/Bonera#4]
Hey!, I love your addon, and I'm missing the ability to do the same you can do with vertices or curves of going into edit mode and selecting a bunch of lattice vertices and being able to create bones for them, it'd be a blessing!
thank you

**Comment by BlenderBoi** [comment]
Good Idea, I will implement in in this week

**Comment by lucianomunoz** [comment]
That'd be sick ! thank you!!!

Luciano A. Muñoz Sessarego

*Character Animator*

Web: www.pintamonos.cl

Email: ***@***.***

Imdb: www.imdb.com/name/nm8355386/

Insta: www.instagram.com/lucianomunoz

Linkedin: www.linkedin.com/in/lucianomunoz

Youtube: www.youtube.com/theadventuresoflollypopman

**Comment by BlenderBoi** [comment]
Here is the preview of the requested feature

https://www.youtube.com/watch?v=11cIcJAqYj4

It is not release yet, I will do some stress test before I release, probably within this week

Hopefully you like it

**Comment by lucianomunoz** [comment]
holy smokes thats better than what i had even thought about!!
awesomeee!
id love to play with it!

Luciano A. Muñoz Sessarego
Web: www.pintamonos.cl
Email: ***@***.***
Vimeo: www.vimeo.com/lucianomunoz
Gumroad: https://gumroad.com/lucianomunoz
Imdb: https://www.imdb.com/name/nm8355386/
Linkedin: http://www.linkedin.com/in/lucianomunoz

**Comment by BlenderBoi** [comment]
https://github.com/BlenderBoi/Bonera/releases/tag/v1.4.1

Download Link Here

**Comment by lucianomunoz** [comment]
Thank you!

Luciano A. Muñoz Sessarego

*Character Animator*

Web: www.pintamonos.cl

Email: ***@***.***

Imdb: www.imdb.com/name/nm8355386/

Insta: www.instagram.com/lucianomunoz

Linkedin: www.linkedin.com/in/lucianomunoz

Youtube: www.youtube.com/theadventuresoflollypopman
